# ===================================================================
# File Uploads Streams and Batch configurations
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# Configure list-page sizes
reader:
  data_table:
      list:
         size: 5
  deposit:
      list:
        size: 5000
spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    configuration:
                        max.request.size: 90000000
                        max.poll.interval.ms: 300000
                        session.timeout.ms: 300000
                        group.max.session.timeout.ms: 300000
            bindings:
                greetings-in:
                    destination: greetings
                    contentType: application/json
                greetings-out:
                    destination: greetings
                    contentType: application/json
                file-notifications-in:
                    destination: fileNotications
                    contentType: application/json
                file-notifications-out:
                    destination: fileNotications
                    contentType: application/json
                json-deposits-create-inbound:
                    destination: jsonStringStreamsDepositsCreate
                    contentType: application/json
                json-deposits-create-outbound:
                    destination: jsonStringStreamsDepositsCreate
                    contentType: application/json
